In [1]:
import os
import numpy as np
import pandas as pd
from datetime import datetime
import pytz
import requests


from dateutil.parser import parse as parsedate

###  Static URL's of public data from EIA

In [2]:
    # EIA_DL_URL = 'http://ir.eia.gov/wpsr/psw09.xls'
    # EIA_OUTFILE= '../data/psw09.xls'
    # #source of historical pricing
    # EIA_OIL_PRICE_URL = 'http://www.eia.gov/dnav/pet/hist_xls/RCLC1w.xls'
    # EIA_OIL_PRICE_OUTFILE = '../data/RCLC1w.xls'

    # EIA_OIL_FUTURES = 'https://www.eia.gov/dnav/pet/xls/PET_PRI_FUT_S1_W.xls'
    # EIA_OIL_FUTURES_OUTFILE = '../data/futures.xls'

In [3]:
def get_file(url, out):
    response = requests.get(url)
    totalbits = 0
    if response.status_code == 200:
        with open(out, 'wb') as f:
            for chunk in response.iter_content(chunk_size=1024):
                if chunk:
                    totalbits += 1024
                    f.write(chunk)
    print(f"Downloaded from {url} file = ",totalbits*1025,"KB...")

### Fetch EIA xls sheet and convert to csv

In [4]:
#operation = 'reserves'
# #operation = 'pricing'
# operation = 'futures'

# if operation == 'reserves':
#     url = EIA_DL_URL
#     out = EIA_OUTFILE

# if operation == 'pricing':
#     url = EIA_OIL_PRICE_URL
#     out = EIA_OIL_PRICE_OUTFILE

# if operation == 'futures':
#     url = EIA_OIL_FUTURES
#     out = EIA_OIL_FUTURES_OUTFILE

### Process EIA spreadsheets and convert to .csv for reading by other processes

In [5]:
EIA_DL_URL = 'http://ir.eia.gov/wpsr/psw09.xls'
EIA_OUTFILE= '../data/psw09.xls'

# Fetch the xls file
get_file(EIA_DL_URL, EIA_OUTFILE)

# Pipeline data conversion to .csv
df = pd.read_excel(open(EIA_OUTFILE, 'rb'),
                   skiprows=1,
                   sheet_name='Data 6'
                   #converters= {'Date': pd.to_datetime},
                   #index_col='Date'
                  )
df = df.drop([0]) #remove desc
df.rename(columns={'Sourcekey':'Date'},inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

file_name = "../data/all_eia_stock_sheet_latest.csv"
df.to_csv(file_name, sep=',', encoding='utf-8')
df.tail(5)

Downloaded from http://ir.eia.gov/wpsr/psw09.xls file =  8246707200 KB...

,WCRSTUS1,WCESTUS1,WCESTP11,WCESTP21,W_EPC0_SAX_YCUOK_MBBL,WCESTP31,WCESTP41,WCESTP51,W_EPC0_SKA_NUS_MBBL,WCSSTUS1,...,WPRST_R4N5_1,W_EPLLP0C_SKB_NUS_MBBL,WPLSTUS1,W_EPPO6_SAE_NUS_MBBL,WUOSTUS1,W_EPPK_SAE_NUS_MBBL,W_EPPA_SAE_NUS_MBBL,W_EPL0XP_SAE_NUS_MBBL,WTESTUS1,WTTSTUS1
Date,,,,,,,,,,,,,,,,,,,,,
2023-10-20,772394,421120,7648,102642,21226,242485,23409,44935,3457,351274,...,5933,NaN,NaN,316003,84316,1352,21592,176084,1265613,1616887
2023-10-27,773167,421893,7928,103694,21498,241784,23460,45028,3769,351274,...,5904,NaN,NaN,315712,86679,1305,20832,174235,1262562,1613836
2023-11-03,787036,435762,8727,103930,23085,253217,23242,46646,2348,351274,...,5946,NaN,NaN,316868,89626,1233,20910,172354,1263726,1615000
2023-11-10,790628,439354,9506,108142,25010,252373,22855,46478,2485,351274,...,6958,NaN,NaN,317788,89968,1405,20813,172382,1263666,1614940
2023-11-17,799328,448054,8415,109221,25868,257894,24195,48329,3598,351274,...,6912,NaN,NaN,312264,87583,1297,21154,168814,1268129,1619403

In [6]:
EIA_OIL_PRICE_URL = 'http://www.eia.gov/dnav/pet/hist_xls/RCLC1w.xls'
EIA_OIL_PRICE_OUTFILE = '../data/RCLC1w.xls'

get_file(EIA_OIL_PRICE_URL, EIA_OIL_PRICE_OUTFILE )

df = pd.read_excel(open(EIA_OIL_PRICE_OUTFILE, 'rb'),
                   skiprows=1,
                   sheet_name='Data 1'
                   #converters= {'Date': pd.to_datetime},
                   #index_col='Date'
                  )
df = df.drop([0]) #remove desc
df.rename(columns={'Sourcekey':'Date'},inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

file_name = "../data/eia_pricing_latest.csv"
df.to_csv(file_name, sep=',', encoding='utf-8')
df.tail(5)

Downloaded from http://www.eia.gov/dnav/pet/hist_xls/RCLC1w.xls file =  128051200 KB...

            RCLC1
Date
2023-10-20  87.95
2023-10-27  84.67
2023-11-03  81.35
2023-11-10  77.29
2023-11-17  76.39

In [7]:
EIA_OIL_FUTURES = 'https://www.eia.gov/dnav/pet/xls/PET_PRI_FUT_S1_W.xls'
EIA_OIL_FUTURES_OUTFILE = '../data/futures.xls'

get_file(EIA_OIL_FUTURES, EIA_OIL_FUTURES_OUTFILE)

df = pd.read_excel(open(EIA_OIL_FUTURES_OUTFILE, 'rb'),
                   skiprows=1,
                   sheet_name='Data 1'
                   #converters= {'Date': pd.to_datetime},
                   #index_col='Date'
                  )
df = df.drop([0]) #remove desc
df.rename(columns={'Sourcekey':'Date'},inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

file_name = "../data/eia_futures_latest.csv"
df.to_csv(file_name, sep=',', encoding='utf-8')
df.tail(5)

Downloaded from https://www.eia.gov/dnav/pet/xls/PET_PRI_FUT_S1_W.xls file =  702182400 KB...

            RCLC1  RCLC2  RCLC3  RCLC4
Date
2023-10-20  87.95  86.88  85.66   84.5
2023-10-27  84.67  83.86  83.02  82.24
2023-11-03  81.35  80.93  80.43  79.91
2023-11-10  77.29   77.2  76.98  76.74
2023-11-17  76.39  76.46  76.41  76.32